### ISSUE TITLE
New line

### ISSUE THREAD

**Issue by plegrand1** [step-/gtkmenuplus#4]
Hello,
what is the way to add a new line (cr lf) in an item or tooltip definition ?

In my case : 
`tooltip = <span foreground='#FFFFFF' background='#C02942' weight='bold' size='12000'>Windows XP *new line* 192.168.151.240 *new line* 192.168.39.240 *new line* Fitec, Matlab, Catia </span>`

Thanks for your help

**Comment by step-** [comment]
Hi,

> How can I embed newlines in `item=` and `tooltip=` directives?

You can use a variable and set it to the output of the `printf` shell command.  Include the newlines inside printf's arguments.  Here's an example template (first item) and your case worked out in two slightly different ways (items 3 and 4).

```awk
twolines == printf "1\n2"
item = $twolines
tooltip = $twolines
separator

separator
tt3 == printf '<span foreground="#FFFFFF" background="#C02942" weight="bold" size="12000">%s\n</span>' "Windows XP" 192.168.151.240 192.168.39.240 "Fitec, Matlab, Catia"
item = 3
tooltip = $tt3

separator
tt4 == printf '<span foreground="#FFFFFF" background="#C02942" weight="bold" size="12000">Windows XP\n192.168.151.240\n192.168.39.240\nFitec, Matlab, Catia</span>'
item = 4
tooltip = $tt4
```
Note that I used `\n` for a newline.  You asked for "cr lf", which is newline in Windows.  For *nix operating systems "lf" is enough. If you really need "cr lf" replace `\n` with `\r\n`.

Item 3 outputs a whole span for each line complete with a newline. Item 4 outputs a single span with embedded newlines. The visual difference between the two is a dangling, unformatted newline in item 3.

So, the general method to do complex item and tooltip formatting is to set a variable with a shell command using the `==` assignment operator, which captures the output of the shell command.  You can use any shell command that meets your need.  The variable must be set before starting the item block that uses the value to fill any of its components (item, cmd, icon and tooltip).

**Comment by step-** [comment]
I'm closing this item. Feel free to reopen it if you have more questions.
