### ISSUE TITLE
Run on windows

### ISSUE THREAD

**Issue by plegrand1** [step-/gtkmenuplus#6]
Hello,
i have to change my pro computer and the new one will be on Windows OS.
What could be the way to run gtkplus on windows ?

Thanks for your help

**Comment by step-** [comment]
I've only built and tested gtkmenuplus on Linux with GTK+-2 and GTK+-3.  Theoretically GTK is/was available for Windows [more info](https://en.wikipedia.org/wiki/GTK#Windows).
So one way to run gtkmenuplus on Windows would be to clone this repo, install GTK+-2 or 3 for Windows, and try to compile this project for Windows.  I have no idea how hard that would be, and if it would even work for Windows 10 or 11.
Another possibility to run gtkmenuplus on Windows is to install Windows WSL 2 on Windows 10 or 11, which would let you run Linux programs in the Windows desktop [more info](https://docs.microsoft.com/en-us/windows/wsl/tutorials/gui-apps).

**Comment by plegrand1** [comment]
Many thanks for your answer.
